spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/librarymanage
    username: postgres
    password: mgmg0530
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  
  batch:
    job:
      enabled: false
  
  web:
    cors:
      allowed-origins: 
        - "http://localhost:3000"
        - "http://127.0.0.1:3000"
      allowed-methods: "*"
      allowed-headers: "*"
  
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

# JWT設定
app:
  jwtSecret: mySecretKeyForLibraryManagementSystem2024!@#$%^&*()_EXTENDED_FOR_HS512_ALGORITHM_MINIMUM_LENGTH_REQUIREMENT
  jwtExpirationMs: 3600000    # 1時間 (60 * 60 * 1000)
  jwtRefreshExpirationMs: 604800000  # 7日間 (7 * 24 * 60 * 60 * 1000)